$ErrorActionPreference = "Stop"

$root = "D:\git\content-ops-platform"
$apiBase = "http://127.0.0.1:3000/api"
$userId = "user_local_default"
$nodeDir = "C:\Users\lc\AppData\Local\ms-playwright-go\1.50.1"

function Invoke-Json {
  param(
    [Parameter(Mandatory = $true)][string]$Method,
    [Parameter(Mandatory = $true)][string]$Url,
    [Parameter(Mandatory = $false)]$Body
  )

  $headers = @{
    "x-user-id" = $userId
  }

  if ($null -eq $Body) {
    return Invoke-RestMethod -Method $Method -Uri $Url -Headers $headers
  }

  $jsonBody = $Body | ConvertTo-Json -Depth 8
  return Invoke-RestMethod -Method $Method -Uri $Url -Headers $headers -ContentType "application/json" -Body $jsonBody
}

Write-Host "Starting API..."
$job = Start-Job -ScriptBlock {
  param($rootPath, $nodePath)
  $env:PATH = "$nodePath;$env:PATH"
  Set-Location $rootPath
  pnpm.cmd --dir $rootPath dev:api
} -ArgumentList $root, $nodeDir

Start-Sleep -Seconds 6

try {
  $health = Invoke-Json -Method "GET" -Url "$apiBase/health"
  Write-Host "Health:" ($health | ConvertTo-Json -Compress)

  $markdown = @"
# API Smoke Test Article

This article is generated by smoke test.
"@

  $stamp = [DateTimeOffset]::UtcNow.ToUnixTimeSeconds()
  $title = "API Smoke Test Article $stamp"

  $importResp = Invoke-Json -Method "POST" -Url "$apiBase/content/import-markdown" -Body @{
    title = $title
    summary = "Smoke test content"
    markdownBody = $markdown
    tags = @("smoke", "api")
    sourceType = "MARKDOWN"
  }
  Write-Host "Import:" ($importResp | ConvertTo-Json -Compress)

  $contentId = $importResp.data.contentId
  $versionId = $importResp.data.versionId

  $themes = Invoke-Json -Method "GET" -Url "$apiBase/themes?platform=WECHAT_OFFICIAL"
  Write-Host "Themes Count:" $themes.data.items.Count

  $preview = Invoke-Json -Method "POST" -Url "$apiBase/themes/render-preview" -Body @{
    themeCode = "wechat-tech-green"
    platform = "WECHAT_OFFICIAL"
    markdownBody = "## Preview`nHello"
    title = "Preview"
  }
  Write-Host "Preview HTML length:" $preview.data.html.Length

  $accountResp = Invoke-Json -Method "POST" -Url "$apiBase/channel-accounts" -Body @{
    platform = "WECHAT_OFFICIAL"
    name = "Smoke Account"
    credentials = @{
      appId = "mock_app"
      appSecret = "mock_secret"
    }
    meta = @{
      author = "Smoke Bot"
      defaultThumbMediaId = "replace_thumb_media_id"
    }
  }
  Write-Host "Account:" ($accountResp | ConvertTo-Json -Compress)
  $accountId = $accountResp.data.id

  $draftResp = Invoke-Json -Method "POST" -Url "$apiBase/drafts" -Body @{
    contentId = $contentId
    versionId = $versionId
    channelAccountId = $accountId
    themeCode = "wechat-tech-green"
    platform = "WECHAT_OFFICIAL"
  }
  Write-Host "Draft Job:" ($draftResp | ConvertTo-Json -Compress)
  $jobId = $draftResp.data.publishJobId

  $draftDetail = Invoke-Json -Method "GET" -Url "$apiBase/drafts/$jobId"
  Write-Host "Draft Detail:" ($draftDetail | ConvertTo-Json -Compress)

  Write-Host "Smoke test completed."
}
finally {
  Stop-Job -Job $job -ErrorAction SilentlyContinue | Out-Null
  Receive-Job -Job $job -Keep -ErrorAction SilentlyContinue | Out-Null
  Remove-Job -Job $job -Force -ErrorAction SilentlyContinue | Out-Null
}
